[package]
name = "latviz"
version = "0.1.0"
edition = "2021"

[dependencies]
poloto = "5.19.1"
serde_json = "1.0.79"
serde = { version = "1.0.136", features = ["derive"] }

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
panic = "abort"